#!/usr/bin/env bash
# Cut a release: bump CMakeLists PROJECT_VERSION, commit, tag, and push — all in
# one step, so the tag can never drift from the version the bundles report. CI's
# "Version check" job enforces the same invariant, but doing it here means you
# never push a mismatch in the first place.
#
#   scripts/release.sh 0.1.4
#
# Versioning: SemVer. Pre-1.0 we use 0.MINOR.PATCH (MINOR = features / notable
# changes, PATCH = fixes). Release notes are auto-generated by release.yml from
# the merged PRs since the previous tag.
set -euo pipefail

VERSION="${1:-}"
if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "usage: scripts/release.sh X.Y.Z   (e.g. 0.1.4)" >&2
  exit 1
fi

cd "$(dirname "$0")/.."
TAG="v$VERSION"

# --- preconditions -----------------------------------------------------------
[[ -z "$(git status --porcelain)" ]] || { echo "error: working tree is dirty — commit or stash first." >&2; exit 1; }

BRANCH=$(git rev-parse --abbrev-ref HEAD)
[[ "$BRANCH" == "main" ]] || { echo "error: releases are cut from main (on '$BRANCH')." >&2; exit 1; }

git fetch --quiet origin main --tags
[[ -z "$(git rev-list HEAD..origin/main)" ]] || { echo "error: local main is behind origin/main — pull first." >&2; exit 1; }
git rev-parse -q --verify "refs/tags/$TAG" >/dev/null && { echo "error: tag $TAG already exists." >&2; exit 1; }

CUR=$(grep -oE 'VERSION[[:space:]]+[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt | head -1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
echo "Releasing $CUR -> $VERSION  (tag $TAG)"

# --- bump, commit, tag, push -------------------------------------------------
# Only the project() VERSION line (line ~4), not cmake_minimum_required etc.
perl -0pi -e "s/(project\(ComposersDesktopPlugin\s*\n\s*VERSION )\Q$CUR\E/\${1}$VERSION/" CMakeLists.txt
grep -qE "VERSION $VERSION\b" CMakeLists.txt || { echo "error: failed to update PROJECT_VERSION in CMakeLists.txt." >&2; exit 1; }

git add CMakeLists.txt
git commit -q -m "release: set version $VERSION"
git tag "$TAG"
git push origin main
git push origin "$TAG"

echo "✓ pushed $TAG — release.yml is building it:"
echo "  https://github.com/cdp-wasm-suite/cdp-plugin/actions/workflows/release.yml"
